// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1cb399dd-611b-4ecc-b2df-63aba41a9f22";
const char DEVICE_KEY[]         = "hccb7YM9tYqgY48eKgpHclWJ8";

String minhaSSID;
String minhaSenha;

// variaveis do Arduino Cloud
void commandChange();
void lightChange();

String consoleComando;
String statusSistema;
float temperatura;
CloudColoredLight luzInteligente;
int luminosidade;

// conexão só é criada após inserir senha
WiFiConnectionHandler *ArduinoIoTPreferredConnection;

void initProperties(){
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  
  ArduinoCloud.addProperty(consoleComando, READWRITE, ON_CHANGE, commandChange);
  ArduinoCloud.addProperty(statusSistema, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(luzInteligente, READWRITE, ON_CHANGE, lightChange);
  ArduinoCloud.addProperty(luminosidade, READ, ON_CHANGE, NULL);
}   